

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.1:5432/postgre
 #   url: jdbc:mysql://hadoop102:3306/company_case?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  #  driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8580
csv:
  file:
    epbparty-path: C:\Users\HP\Desktop\epbparty.csv
    epbparty-title: authority,body,caseNo,dataType,epbpartyId,eventLevel,eventName,eventResult,eventYiju,legalRepresentative,money,pname,postTime,sortTime,title
    epbparty-jkqy-path: C:\Users\HP\Desktop\epbparty-jkqy.csv
    epbparty-jkqy-title: eventName,eventType,dataType,epbparty_jkqyId,pname
    epbparty-zxjc-path: C:\Users\HP\Desktop\epbparty-zxjc.csv
    epbparty-zxjc-title: epbparty_zxjcId,creditNo,dealWay,dealWhere,density,eventResult,monitorWay,pname,pollutant,sortTime,standard,station,dataType
    satparty-qs-path: C:\Users\HP\Desktop\satparty-qs.csv
    satparty-qs-title:
    satparty-chufa-path: C:\Users\HP\Desktop\satparty-chufa.csv
    satparty-chufa-title:
    satparty-xin-path: C:\Users\HP\Desktop\satparty-xin.csv
    satparty-xin-title:
    satparty-reg-path: C:\Users\HP\Desktop\satparty-reg.csv
    satparty-reg-title:
    satparty-xuke-path: C:\Users\HP\Desktop\satparty-xuke.csv
    satparty-xuke-title:
    cpws-path: C:\Users\HP\Desktop\cpws.csv
    cpws-title:
    ktgg-path: C:\Users\HP\Desktop\ktgg.csv
    ktgg-title:
    zxgg-path: C:\Users\HP\Desktop\zxgg.csv
    zxgg-title:
    shixin-path: C:\Users\HP\Desktop\shixin.csv
    shixin-title:
    fygg-path: C:\Users\HP\Desktop\fygg.csv
    fygg-title:
    ajlc-path: C:\Users\HP\Desktop\ajlc.csv
    ajlc-title:
    bgt-path: C:\Users\HP\Desktop\bgt.csv
    bgt-title:
    sifacdk-path: C:\Users\HP\Desktop\sifacdk.csv
    sifacdk-title:



    company-case-path: C:\Users\HP\Desktop\company-case.csv
    company-case-title: anyou,case_noo,court,result_amount,result_data_type,result_entry_id,result_level,result_name,result_summary,result_ymd
    litigation-related-path: C:\Users\HP\Desktop\litigation-related.csv
    litigation-related-title: body,data_type,entry_id,sort_time,sort_time_string,title

    revenue-related-path: C:\Users\HP\Desktop\revenue-related01.csv
    revenue-related-title: body,data_type,entry_id,sort_time,sort_time_string,title

    env-protection-path: C:\Users\HP\Desktop\env-protection.csv
    env-protection-title: body,data_type,entry_id,sort_time,sort_time_string,title

