spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://192.168.1.1:5432/postgre
 #   url: jdbc:mysql://hadoop102:3306/company_case?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  #  driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8580
